### ISSUE TITLE
Plex module links have 'False' as the server ID

### ISSUE THREAD

**Issue by Wraithers** [gugahoi/maraschino#15]
This is continued from the discussion on Maraschino Plex support (https://github.com/mrkipling/maraschino/pull/285)

As per your suggestion, I ran Maraschino (via command-line) on my host IP. The command was: `Maraschino.py --host=192.168.1.160`. When I hovered over any media in the Plex module or opened it, the server ID was still 'False'. For clarification, I also use `192.168.1.160` as the Plex server IP address in its module settings. My Plex module settings are in the picture attached.

![screenshot 39](https://f.cloud.github.com/assets/4705057/2470710/6737de94-b017-11e3-9f1b-3ba91fe0cf0f.png)

**Comment by gugahoi** [comment]
I am switching the way maraschino will find servers. I will make it so that every 6 hours I will poll plex's website and store all the server info in maraschino's db (including the server id needed to link to the plex.tv interface), this will help with load times and also make information readily accessible to the module. I will hopefully push that Friday some time.

I think I wasnt very clear in my previous post, you dont need to use the --host parameter I was referring to the "Plex Server IP Address" whan I said maraschino's own settings.

**Comment by gugahoi** [comment]
Btw this is where I am getting the info from: http://plex.tv/pms/servers.xml

**Comment by Wraithers** [comment]
Ah, I see that it should be pulling the `machineIdentifier` (below `MediaContainer`) for the server ID, but it doesn't seem to be doing that currently. Your proposal to store it in maraschino's db sounds promising.

Yup, I had a feeling you meant that about the settings, however I wanted to make sure I tried everything before opening an issue =)

**Comment by Wraithers** [comment]
Fixed with the latest commit (0a9094de99dd946a12b5d16cab7baf71e1efe811)
